networks:
  loki:

services:
  loki:
    image: grafana/loki:3.0.0
    volumes:
      - ~/docker/grafana_loki_promtail_aciek/loki:/loki
      - ~/docker/grafana_loki_promtail_aciek:/tmp/loki/config
    ports:
      - "3100:3100"
    command: -config.file=/tmp/loki/config/loki-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:3.0.0
    volumes:
      - /var/log:/var/log
      - ~/docker/grafana_loki_promtail_aciek:/tmp/promtail/config
    command: -config.file=/tmp/promtail/config/promtail-config.yaml
    networks:
      - loki
  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    volumes:
      - ~/docker/grafana_loki_promtail_aciek/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - loki
