server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://192.168.56.14:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - almalinux
    labels:
      job: varlogs
      node: "almalinux"
      __path__: /var/log/{messages,secure,dmesg,maillog,yum.log,boot.log,cron,alternatives.log,auth.log,bootstrap.log,cloud-init.log.dmesg,dpkg.log,kern.log,syslog,ubuntu-advantage.log,ubuntu-advantage-timer.log}
- job_name: nginx
  static_configs:
  - targets:
      - almalinux
    labels:
      job: nginx
      node: "almalinux"
      __path__: /var/log/nginx/{access,error}*log
- job_name: apache
  static_configs:
  - targets:
      - almalinux
    labels:
      job: apache
      node: "almalinux"
      __path__: /var/log/{apache,httpd}/*log
- job_name: vsftpd
  static_configs:
  - targets:
      - almalinux
    labels:
      job: vsftpd
      node: "almalinux"
      __path__: /var/log/xferlog
- job_name: journal-var
  journal:
    json: false
    max_age: 12h
    path: /var/log/journal
    labels:
      job: systemd-journal
      node: "almalinux"
  relabel_configs:
    - source_labels: ['__journal__systemd_unit']
      target_label: 'unit'
